### ISSUE TITLE
require crash

### ISSUE THREAD

**Issue by cczscq** [mkottman/AndroLua#16]
test_json.lua:
require("json")
function functionInLuaFile(key)
    return 'Require Function in test_json file . Return : '..key..'!'
end

json is a module. In test_json.lua when I require json module, the application crash.

**Comment by xingchch** [comment]
Could you please let me know how to solve this issue? when i require a module defined by myself, the application always crash.

**Comment by xingchch** [comment]
This was caused by coding logical error. Before you require a module. this module must loaded into luastate. otherwise, luastate can not found the module. and add traceback to debug you lua will make program more clear.

**Comment by AnonymousDapper** [comment]
How exactly do you add the module into luastate?
