### ISSUE TITLE
Make File for building .so file

### ISSUE THREAD

**Issue by SatheeshJM** [mkottman/AndroLua#2]
Ok, this is not an AndroLua issue, but i did not know where else to post this.

I am using Gideros engine,  and I need to do a few modifications to the C++ source file and build the shared library again for using with Gideros. 

Can you include the 'make file' which you used to build the shared library along with the .so file?

**Comment by mkottman** [comment]
There is no Makefile for AndroLua. It was build using the NDK, which uses its own `Android.mk` files. It should be relatively simple to follow the logic - just create a Lua library (static or shared), then compile LuaJava and link it to the Lua library. See the [Lua `Android.mk`](https://github.com/mkottman/AndroLua/blob/master/jni/lua/Android.mk) and [LuaJava `Android.mk`](https://github.com/mkottman/AndroLua/blob/master/jni/luajava/Android.mk).

To build the project (for Android), just issue `$(NDK)/ndk-build` in the project directory (where `$NDK`  is the path to your NDK installation).
